[ja]
  title = "TOP PAGE"
  languageName = "Japanese"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/"

[en]
  title = "TOP PAGE"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
