[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 2

[[main]]
  identifier = "programming"
  name = "Programming"
  url = "programming"
  weight = 3

[[main]]
  identifier = "apple"
  name = "Apple"
  url = "apple"
  weight = 4

[[main]]
  identifier = "book"
  name = "書評"
  url = "book"
  weight = 5

[[main]]
  identifier = "qualification"
  name = "資格"
  url = "qualification"
  weight = 6

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 7
